//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zadatak1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ispiti
    {
        public int sifraPremeta { get; set; }
        public int indeks { get; set; }
        public System.DateTime datum { get; set; }
        public int ocena { get; set; }
    
        public virtual Predmeti Predmeti { get; set; }
        public virtual Studenti Studenti { get; set; }
    }
}
