//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zadatak1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StudentiDBEntities : DbContext
    {
        public StudentiDBEntities()
            : base("name=StudentiDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Predmeti> Predmetis { get; set; }
        public virtual DbSet<Studenti> Studentis { get; set; }
        public virtual DbSet<Ispiti> Ispitis { get; set; }
    }
}
